spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8000
logging:
  level:
    org.springframework.jdbc.datasource.init: debug
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9000
