INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly 1', 'P1', '1Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly 2', 'P2', '2Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly 3', 'P3', '3Q');
INSERT INTO ROOM(NAME, ROOM_NUMBER, BED_INFO) VALUES ('Picadilly 4', 'P4', '4Q');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('0d7450a8-1db5-4a05-abdd-3dee6388a431', 'Jorge', 'Lameiro', 'HOUSEKEEPING');
INSERT INTO EMPLOYEE(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, POSITION) VALUES ('00bebc7a-ca85-4287-a05f-e7d95711d4c7', 'Bryana', 'Morales', 'FRONT_DESK');